name: personal_notes_app
description: "A local-first Flutter notes application for quickly creating, editing, and organizing personal notes. Built as an academic/portfolio project to demonstrate mobile UI design, state management, and offline persistence with SQLite."
publish_to: 'none'
version: 1.2.1+6

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  share_plus: ^10.1.4
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true